config/routes.rb
Rails.application.routes.draw do
  resources :csv_uploaders
  resources :months, only: [:new, :create, :update, :destroy]
  resources :paychecks
  resources :transactions, only: [:create, :update, :destroy]
  resources :items, only: [:create, :update, :destroy]
  resources :categories, only: [:create, :update, :destroy]
  devise_for :users 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/category_items', to: 'category_item#index'
  post '/add_transactions', to: 'csv_uploaders#add_transactions', as: 'add_transactions'
  get '/month/:month/year/:year', to: 'category_item#month', as: 'get_month'
  get '/cp', to: 'category_item#cp', as: 'control_panel'
  match '/search-month', to: 'category_item#search', via: :post
  root to: 'home#index'
end

app/models/csv_uploader.rb
class CsvUploader < ApplicationRecord
  has_one_attached :csvbank
  belongs_to :month
end

app/controllers/csv_uploaders_controller.rb
class CsvUploadersController < ApplicationController
  require 'csv'
  before_action :set_csv_uploader, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /csv_uploaders
  # GET /csv_uploaders.json
  def index
    @csv_uploaders = CsvUploader.all
  end

  # GET /csv_uploaders/1
  # GET /csv_uploaders/1.json
  def show
    @csvheaders = CSV.parse(CsvUploader.find(params[:id]).csvbank.download)[0] 

  end

  def add_transactions
    @csvbanks = CSV.parse(CsvUploader.find(params[:id]).csvbank.download, headers: true)
  end

  # GET /csv_uploaders/new
  def new
    @months = Month.where(user_id: current_user.id).all
    @csv_uploader = CsvUploader.new
  end

  # GET /csv_uploaders/1/edit
  def edit
  end

  # POST /csv_uploaders
  # POST /csv_uploaders.json def create
  def create
    @csv_uploader = CsvUploader.new(csv_uploader_params)

    respond_to do |format|
      if @csv_uploader.save
        format.html { redirect_to @csv_uploader, notice: 'Csv uploader was successfully created.' }
        format.json { render :show, status: :created, location: @csv_uploader }
      else
        format.html { render :new }
        format.json { render json: @csv_uploader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /csv_uploaders/1
  # PATCH/PUT /csv_uploaders/1.json
  def update
    respond_to do |format|
      if @csv_uploader.update(csv_uploader_params)
        format.html { redirect_to @csv_uploader, notice: 'Csv uploader was successfully updated.' }
        format.json { render :show, status: :ok, location: @csv_uploader }
      else
        format.html { render :edit }
        format.json { render json: @csv_uploader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /csv_uploaders/1
  # DELETE /csv_uploaders/1.json
  def destroy
    @csv_uploader.destroy
    respond_to do |format|
      format.html { redirect_to csv_uploaders_url, notice: 'Csv uploader was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_csv_uploader
      @csv_uploader = CsvUploader.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def csv_uploader_params
      params.require(:csv_uploader).permit(:month_id, :name, :csvbank)
    end
end

app/helpers/csv_uploaders_helper.rb
module CsvUploadersHelper
end

app/views/csv_uploaders/_form.html.erb
<%= form_with(model: csv_uploader, local: true) do |form| %>
  <% if csv_uploader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(csv_uploader.errors.count, "error") %> prohibited this csv_uploader from being saved:</h2>

      <ul>
        <% csv_uploader.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :month_id, "Select Month" %>
    <%= form.collection_select :month_id, @months, :id, :month_year, class: "form-control"%>

  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :csvbank, "CSV File Uploader"%>
    <%= form.file_field :csvbank, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-dark"%>
  </div>
<% end %>

app/views/csv_uploaders/add_transactions.html.erb
  <div class="category">
    <h2 class="category-title">Proposed Transactions</h2>
    <% @csvbanks.each do |csv| %>
      <div class="card font-weight-bold my-2">
        <div class="card-body d-flex">
          <div class="flex-grow-1"><%= csv[params[:description]] %></a></div>
          <div class="text-info mr-2"><%= csv[params[:date]] %></div>
            <div class="text-danger">
              $ <%= csv[params[:amount]]%>
            </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/csv_uploaders/edit.html.erb
<h1>Editing Csv Uploader</h1>

<%= render 'form', csv_uploader: @csv_uploader %>

<%= link_to 'Show', @csv_uploader %> |
<%= link_to 'Back', csv_uploaders_path %>

app/views/csv_uploaders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Csv Uploaders</h1>

<table>
  <thead>
    <tr>
      <th>Month</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @csv_uploaders.each do |csv_uploader| %>
      <tr>
        <td><%= csv_uploader.month_id %></td>
        <td><%= csv_uploader.name %></td>
        <td><%= link_to 'Show', csv_uploader %></td>
        <td><%= link_to 'Edit', edit_csv_uploader_path(csv_uploader) %></td>
        <td><%= link_to 'Destroy', csv_uploader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Csv Uploader', new_csv_uploader_path %>

app/views/csv_uploaders/new.html.erb
<div class="card mx-auto my-5 shadow" style="max-width: 750px;">
    <div class="card-header bg-dark text-white">
        <h1>New Csv Uploader</h1>
    </div>

    <div class="card-body">
        <%= render 'form', csv_uploader: @csv_uploader %>

        <%= link_to 'Back', csv_uploaders_path %>
    </div>
</div>

app/views/csv_uploaders/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Month:</strong>
    <%= @csv_uploader.month_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @csv_uploader.name %>
  </p>
  <p>
    <%= @csvheaders.inspect %>
  </p>
  <div class="card">
    <div class="card-body">
      <%= form_with url: "/add_transactions", method: "post", :local => {remote: false} do |form| %>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_field :description, class: "form-control"%>
      </div>
        <div class="form-group">
          <%= form.label :amount %>
          <%= form.text_field :amount, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= form.label :date %>
          <%= form.text_field :date, class: "form-control"%>
        </div>
      <%= form.hidden_field :id, value: params[:id] %>

      <%= form.submit class: "btn btn-info"%>
      <% end %>
    </div>
    <% if defined? @listofthings %>
      <%= @listofthings.inspect %>


    <% end %>
  </div>


  <%= link_to 'Edit', edit_csv_uploader_path(@csv_uploader) %> |
  <%= link_to 'Back', csv_uploaders_path %>

</div>