config/routes.rb
Rails.application.routes.draw do
  resources :csv_uploaders
  resources :months, only: [:new, :create, :update, :destroy]
  resources :paychecks
  resources :transactions, only: [:create, :update, :destroy]
  resources :items, only: [:create, :update, :destroy]
  resources :categories, only: [:create, :update, :destroy]
  devise_for :users 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/category_items', to: 'category_item#index'
  post '/add_transactions', to: 'csv_uploaders#add_transactions', as: 'add_transactions'
  get '/month/:month/year/:year', to: 'category_item#month', as: 'get_month'
  get '/cp', to: 'category_item#cp', as: 'control_panel'
  match '/search-month', to: 'category_item#search', via: :post
  root to: 'home#index'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /transactions/new
  def new
    @items = Item.all
    @transaction = Transaction.new
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new()

    @transaction.name = params[:transaction][:name]
    @month = Month.where(user_id: current_user.id, month: params[:transaction][:transaction_month], year: params[:transaction][:transaction_year]).first
    @transaction.user_id = current_user.id
    @transaction.item_id = params[:transaction][:item_id]
    @transaction.month_id = @month.id
    @transaction.spent = params[:transaction][:spent]
    @transaction.spent_date = params[:transaction][:spent_date]
    respond_to do |format|
      if @transaction.save
        format.html { 
          flash[:notice]="Successfully Created New Budget Transaction"
          redirect_back fallback_location: '/category_items' 
        }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { 
          @items = Item.all
          render :new 
        }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(name: params[:transaction][:name], item_id: params[:transaction][:item_id], spent: params[:transaction][:spent], spent_date: params[:transaction][:spent_date])
        format.html { redirect_to "/cp", notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { redirect_back fallback_location: "/cp" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: "/cp", notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:name, :user_id, :item_id, :spent, :spent_date, :transaction_month, :transaction_year)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :item_id %>
    <%= form.collection_select :item_id, @items, :id, :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :spent %>
    <%= form.number_field :spent, step: 0.01, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :spent_date %>
    <%= form.datetime_select :spent_date, class:"form-control" %>
  </div>
  <%= form.hidden_field :transaction_month, value: params[:month] %>
  <%= form.hidden_field :transaction_year, value: params[:year] %>

  <div class="actions">
    <%= form.submit class:"btn btn-dark float-right" %>
    <% if(transaction.persisted?) %>
      <%= link_to 'Delete', transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger float-right mr-2" %>
    <% end %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Item</th>
      <th>Spent</th>
      <th>Spent date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.name %></td>
        <td><%= transaction.user_id %></td>
        <td><%= transaction.item_id %></td>
        <td><%= transaction.spent %></td>
        <td><%= transaction.spent_date %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<div class="container">
<h1>New Transaction</h1>

<div class="card">
    <div class="card-body">
        <%= render 'form', transaction: @transaction %>
    </div>
</div>

<%= link_to 'Back', transactions_path %>
</div>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @transaction.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @transaction.user_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @transaction.item_id %>
</p>

<p>
  <strong>Spent:</strong>
  <%= @transaction.spent %>
</p>

<p>
  <strong>Spent date:</strong>
  <%= @transaction.spent_date %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>